### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by anacrolix** [jeffwidman/bitbucket_issue_migration#23]
```
Traceback (most recent call last):
  File "migrate.py", line 304, in <module>
    push_issue(gh_username, gh_repository, issue, body, comments)
  File "migrate.py", line 220, in push_issue
    gh_repository
  File "/usr/local/lib/python2.7/site-packages/pygithub3/services/issues/__init__.py", line 94, in create
    return self._post(request)
  File "/usr/local/lib/python2.7/site-packages/pygithub3/services/base.py", line 139, in _post
    response = self._client.post(request, data=input_data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pygithub3/core/client.py", line 89, in post
    response = self.request('post', request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pygithub3/core/client.py", line 71, in wrapper
    return func(self, verb, request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pygithub3/core/client.py", line 80, in request
    GithubError(response).process()
  File "/usr/local/lib/python2.7/site-packages/pygithub3/core/errors.py", line 36, in process
    self.response.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden
```

**Comment by TurkeyMan** [comment]
+1

**Comment by jeffwidman** [comment]
#25 switched to using Github's import API directly rather than pygithub3 so this shouldn't be an issue anymore.
